### ISSUE TITLE
the file "index.js" is missing in client

### ISSUE THREAD

**Issue by Arm1** [TypedProject/tsed-example-react#1]
First, thks for your work !
It seems that the file index.js is missing in the client folder.
I've put one from a create-react-app, and it seems to work.
(even, if I don't know how your setupProxy works).

Here is the error output when i run "yarn start":
`λ yarn start
yarn run v1.17.3
$ lerna run start --stream --parallel
lerna notice cli v3.18.4
lerna info Executing command in 2 packages: "yarn run start"
@project/client: $ react-scripts start
@project/server: $ nodemon --watch 'src/**/*.ts' --ignore 'node_modules/**/*' --exec ts-node src/index.ts
@project/server: [nodemon] 1.19.4
@project/server: [nodemon] to restart at any time, enter `rs`
@project/server: [nodemon] watching dir(s): 'src\**\*.ts'
@project/server: [nodemon] watching extensions: ts,json
@project/server: [nodemon] starting `ts-node src/index.ts`
@project/client: Could not find a required file.
@project/client:   Name: index.js
@project/client:   Searched in: C:\Dev\TryAndTest\REACT\tsed-example-react\packages\client\src
@project/client: error Command failed with exit code 1.
@project/client: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run start exited 1 in '@project/client'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by Romakita** [comment]
Arf yes... you've right ^^
I'll fix that ;)

**Comment by Romakita** [comment]
setupProxy is loaded automatically by create-react-app :)

**Comment by Romakita** [comment]
Fixed :)
